# Generated by Django 4.2.11 on 2026-07-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khoa', models.CharField(max_length=20, unique=True)),
                ('ten_khoa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NganhDaoTao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nganh', models.CharField(max_length=20, unique=True)),
                ('ten_nganh', models.CharField(max_length=200)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nganh_dao_tao', to='students.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15)),
                ('khoa_hoc', models.CharField(max_length=10)),
                ('nam_nhap_hoc', models.IntegerField()),
                ('da_mien_cdr', models.BooleanField(default=False)),
                ('khoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.khoa')),
                ('nganh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.nganhdaotao')),
            ],
        ),
    ]
