# Generated by Django 4.2.11 on 2026-07-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nganhdaotao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nganhdaotao',
            name='loai_nganh',
            field=models.CharField(choices=[('THUONG', 'Ngành thông thường'), ('NGON_NGU_ANH', 'Ngôn ngữ Anh'), ('NGON_NGU_TRUNG', 'Ngôn ngữ Trung Quốc')], default='THUONG', max_length=30),
        ),
        migrations.AddField(
            model_name='nganhdaotao',
            name='thoi_gian_dao_tao_nam',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='nganhdaotao',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_nganh', to='students.khoa'),
        ),
        migrations.AlterField(
            model_name='nganhdaotao',
            name='ma_nganh',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nganhdaotao',
            name='ten_nganh',
            field=models.CharField(max_length=255),
        ),
    ]
