# Generated by Django 4.2.11 on 2026-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_nganhdaotao_is_active_nganhdaotao_loai_nganh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='lop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
