# Generated by Django 5.2.17 on 2026-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_sinhvien_lop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='email',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_ca_nhan',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cá nhân'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_truong',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email trường'),
        ),
    ]
