# Generated by Django 4.2.11 on 2026-07-07 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LopBoiDuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True)),
                ('ten_lop', models.CharField(max_length=200)),
                ('loai', models.CharField(choices=[('NN', 'Ngoại ngữ'), ('TH', 'Tin học')], max_length=20)),
                ('so_luong_toi_da', models.IntegerField(default=30)),
                ('bat_dau', models.DateField()),
                ('ket_thuc', models.DateField()),
                ('trang_thai', models.CharField(default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinh_vien_id', models.IntegerField()),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(default='PENDING', max_length=20)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.lopboiduong')),
            ],
        ),
    ]
