# Generated by Django 4.2.11 on 2026-08-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lopboiduong',
            name='ma_mh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã môn học'),
        ),
        migrations.AddField(
            model_name='lopboiduong',
            name='nhom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nhóm'),
        ),
        migrations.AddField(
            model_name='lopboiduong',
            name='si_so_hien_tai',
            field=models.IntegerField(default=0, verbose_name='Sĩ số hiện tại'),
        ),
        migrations.AlterField(
            model_name='dangkylop',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dang_ky', to='training.lopboiduong'),
        ),
        migrations.AlterField(
            model_name='dangkylop',
            name='trang_thai',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dangkylop',
            unique_together={('sinh_vien_id', 'lop')},
        ),
        migrations.CreateModel(
            name='LichHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Chủ nhật')], verbose_name='Thứ')),
                ('tiet_bat_dau', models.IntegerField(default=1, verbose_name='Tiết bắt đầu')),
                ('tiet_ket_thuc', models.IntegerField(default=3, verbose_name='Tiết kết thúc')),
                ('phong_hoc', models.CharField(max_length=50, verbose_name='Phòng học')),
                ('giang_vien', models.CharField(blank=True, max_length=100, verbose_name='Giảng viên')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hoc', to='training.lopboiduong')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'ordering': ['thu', 'tiet_bat_dau'],
            },
        ),
    ]
