# Generated by Django 4.2.11 on 2026-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanhBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinh_vien_id', models.IntegerField()),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('muc_do', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung'), ('HIGH', 'Cao')], max_length=20)),
                ('da_gui', models.BooleanField(default=False)),
                ('ngay_gui', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('loai', models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('ACADEMIC', 'Học vụ')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
