# Generated by Django 4.2.11 on 2026-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('hinh_anh', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('duong_dan', models.CharField(max_length=200)),
                ('thu_tu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=100)),
                ('hinh_anh', models.URLField()),
                ('duong_dan', models.CharField(blank=True, max_length=200)),
                ('thu_tu', models.IntegerField(default=0)),
            ],
        ),
    ]
