# Generated by Django 4.2.11 on 2026-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanBanQuyChe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('loai', models.CharField(choices=[('QUY_CHE', 'Quy chế'), ('BIEU_MAU', 'Biểu mẫu'), ('HUONG_DAN', 'Hướng dẫn'), ('VAN_BAN', 'Văn bản khác')], default='QUY_CHE', max_length=20, verbose_name='Loại văn bản')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('file_dinh_kem', models.FileField(blank=True, null=True, upload_to='van_ban/', verbose_name='File đính kèm')),
                ('thu_tu', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Văn bản quy chế',
                'verbose_name_plural': 'Văn bản quy chế',
                'ordering': ['thu_tu', '-created_at'],
            },
        ),
    ]
