# Generated by Django 4.2.11 on 2026-07-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_danh_muc', models.CharField(max_length=20, unique=True)),
                ('ten_danh_muc', models.CharField(max_length=200)),
                ('loai', models.CharField(choices=[('NN', 'Ngoại ngữ'), ('TH', 'Tin học')], max_length=20)),
                ('bac', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinh_vien_id', models.IntegerField()),
                ('so_chung_chi', models.CharField(max_length=50, unique=True)),
                ('ngay_cap', models.DateField()),
                ('ngay_het_han', models.DateField(blank=True, null=True)),
                ('diem_so', models.FloatField(blank=True, null=True)),
                ('hinh_thuc_thi', models.CharField(blank=True, max_length=50)),
                ('trang_thai', models.CharField(default='ACTIVE', max_length=20)),
                ('da_xet_duyet', models.BooleanField(default=False)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.danhmucchungchi')),
            ],
        ),
    ]
