# Generated by Django 5.2.17 on 2026-09-30 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chungchi',
            options={'ordering': ['-ngay_cap']},
        ),
        migrations.AlterField(
            model_name='chungchi',
            name='danh_muc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_chung_chi', to='certificates.danhmucchungchi'),
        ),
        migrations.AlterField(
            model_name='chungchi',
            name='sinh_vien_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='chungchi',
            name='trang_thai',
            field=models.CharField(choices=[('DAT', 'Đạt / Hợp lệ'), ('CHUA_DAT', 'Chưa đạt'), ('CHO', 'Chờ duyệt'), ('TU_CHOI', 'Từ chối'), ('HET_HAN', 'Hết hạn'), ('THU_HOI', 'Thu hồi')], default='CHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='danhmucchungchi',
            name='loai',
            field=models.CharField(choices=[('NGOAI_NGU', 'Ngoại ngữ'), ('TIN_HOC', 'Tin học')], max_length=20),
        ),
    ]
