DROP DATABASE IF EXISTS humg_gateway;
DROP DATABASE IF EXISTS humg_student;
DROP DATABASE IF EXISTS humg_training;
DROP DATABASE IF EXISTS humg_exam;
DROP DATABASE IF EXISTS humg_certificate;
DROP DATABASE IF EXISTS humg_notification;
DROP DATABASE IF EXISTS humg_cms;
DROP DATABASE IF EXISTS humg_report;
DROP USER IF EXISTS humg_gateway;
DROP USER IF EXISTS humg_student;
DROP USER IF EXISTS humg_training;
DROP USER IF EXISTS humg_exam;
DROP USER IF EXISTS humg_certificate;
DROP USER IF EXISTS humg_notification;
DROP USER IF EXISTS humg_cms;
DROP USER IF EXISTS humg_report;
CREATE USER humg_gateway WITH PASSWORD 'gateway_pwd_2026';
CREATE USER humg_student WITH PASSWORD 'student_pwd_2026';
CREATE USER humg_training WITH PASSWORD 'training_pwd_2026';
CREATE USER humg_exam WITH PASSWORD 'exam_pwd_2026';
CREATE USER humg_certificate WITH PASSWORD 'cert_pwd_2026';
CREATE USER humg_notification WITH PASSWORD 'noti_pwd_2026';
CREATE USER humg_cms WITH PASSWORD 'cms_pwd_2026';
CREATE USER humg_report WITH PASSWORD 'report_pwd_2026';
CREATE DATABASE humg_gateway OWNER humg_gateway TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_student OWNER humg_student TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_training OWNER humg_training TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_exam OWNER humg_exam TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_certificate OWNER humg_certificate TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_notification OWNER humg_notification TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_cms OWNER humg_cms TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
CREATE DATABASE humg_report OWNER humg_report TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
GRANT ALL PRIVILEGES ON DATABASE humg_gateway TO humg_gateway;
GRANT ALL PRIVILEGES ON DATABASE humg_student TO humg_student;
GRANT ALL PRIVILEGES ON DATABASE humg_training TO humg_training;
GRANT ALL PRIVILEGES ON DATABASE humg_exam TO humg_exam;
GRANT ALL PRIVILEGES ON DATABASE humg_certificate TO humg_certificate;
GRANT ALL PRIVILEGES ON DATABASE humg_notification TO humg_notification;
GRANT ALL PRIVILEGES ON DATABASE humg_cms TO humg_cms;
GRANT ALL PRIVILEGES ON DATABASE humg_report TO humg_report;
