# Generated by Django 4.2.11 on 2026-07-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.CharField(max_length=20, unique=True)),
                ('ten_dot', models.CharField(max_length=200)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('loai', models.CharField(choices=[('TIN_CHI', 'Tín chỉ'), ('CDR_NN', 'CĐR Ngoại ngữ'), ('CDR_TH', 'CĐR Tin học')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinh_vien_id', models.IntegerField()),
                ('diem', models.FloatField(blank=True, null=True)),
                ('dat', models.BooleanField(default=False)),
                ('so_lan_thi', models.IntegerField(default=1)),
                ('so_lan_bao_luu', models.IntegerField(default=0)),
                ('ghi_chu_vang_thi', models.TextField(blank=True)),
                ('mat_khau', models.CharField(blank=True, max_length=20)),
                ('dot_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.dotthi')),
            ],
        ),
        migrations.CreateModel(
            name='BaoLuuDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinh_vien_id', models.IntegerField()),
                ('diem_bao_luu', models.FloatField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(default='ACTIVE', max_length=20)),
                ('dot_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.dotthi')),
            ],
        ),
    ]
