# Generated by Django 4.2.11 on 2026-08-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsuthi',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='lichsuthi',
            name='diem',
        ),
        migrations.RemoveField(
            model_name='lichsuthi',
            name='ghi_chu_vang_thi',
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='danh_sach_phan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='diem_phan_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='diem_phan_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='diem_phan_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='diem_phan_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='loai',
            field=models.CharField(choices=[('NN', 'Ngoại ngữ'), ('TH', 'Tin học')], default='NN', max_length=2),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baoluudiem',
            name='ngay_het_han',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_chuan_ngoai_ngu',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_chuan_tin_hoc',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_liet_ngoai_ngu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_liet_tin_hoc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='file_thong_bao',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ca_thi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ca_thi_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='co_bao_luu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_tong',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ket_qua_dat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='mon_thi',
            field=models.CharField(choices=[('TA_DAU_VAO', 'Tiếng Anh đầu vào'), ('CDR_NGOAI_NGU', 'CĐR Ngoại ngữ'), ('CDR_TIN_HOC', 'CĐR Tin học')], default='CDR_NGOAI_NGU', max_length=20),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ngay_thi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ngay_thi_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='phong_thi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='phong_thi_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='sbd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='xep_loai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baoluudiem',
            name='diem_bao_luu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='dot_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thi', to='exams.dotthi'),
        ),
    ]
